#!/bin/sh

SRC_PATH=`dirname $0`
MKL_INC_PATH=/usr/include/mkl
MKL_LIB_PATH=/usr/lib/x86_64-linux-gnu

# TODO: try -mavx2 -mfma
CXXFLAGS="-O3 -g"
CXXFLAGS="$CXXFLAGS -DNDEBUG=1 -DBOOST_UBLAS_NDEBUG"
CXXFLAGS="$CXXFLAGS -DYANN_ENABLE_CHECKS=1 -DYANN_DISABLE_SLOW_CHECKS=1"
CXXFLAGS="$CXXFLAGS -I${MKL_INC_PATH}"

LDFLAGS="-O3 -g"
LDFLAGS="$LDFLAGS -L${MKL_LIB_PATH}"

$SRC_PATH/configure CFLAGS= CPPFLAGS= CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" --enable-mkl

if [ ! -e data ]; then
  ln -s $SRC_PATH/data .
fi
