#!/bin/sh

SRC_PATH=`dirname $0`

CXXFLAGS="-g3 -O1 -DDEBUG -DEIGEN_RUNTIME_NO_MALLOC=1 -DYANN_ENABLE_CHECKS=1 -DYANN_ENABLE_SLOW_CHECKS=1"
 
LDFLAGS="-g3"

$SRC_PATH/configure CFLAGS= CPPFLAGS= CXXFLAGS="$CXXFLAGS" LD_FLAGS="$LDFLAGS" 

if [ ! -e data ]; then
  ln -s $SRC_PATH/data .
fi


